In [38]:
import numpy as np

In [39]:
a = np.array([[1,2],[2,3],[3,4]]) #Array using numpy , first
print(a)

[[1 2]
 [2 3]
 [3 4]]


In [40]:
b=np.array([5,10,15,20])
Add = np.add(b,2) #adding two each element in b , second
print(Add)

[ 7 12 17 22]


In [41]:
mul = np.multiply(b,2) #multiplying each element by 2 of b, third
print(mul)

[10 20 30 40]


In [42]:
i=np.matrix('1,2;3,4') #constructing the matrix , used ; for separating rows , fourth
print(i)

[[1 2]
 [3 4]]


In [43]:
b=np.linalg.inv(i) #inverse of matrix  using I and inv both , fifth
print(b)
print(i.I)

[[-2.   1. ]
 [ 1.5 -0.5]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [44]:
print(i.T) #transpose of matrix using T operator , sixth

[[1 3]
 [2 4]]


In [45]:
Identity = np.eye(3) #creating identity matrix using builtin funciton , seventh
print(Identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [46]:
trace = np.trace(Identity) #using trace function for sum of diagonal elements , eighth
print(trace)

3.0


In [62]:
print(np.linalg.matrix_rank(Identity)) #USING MATRIX RANK FUNCTION , ninth

3


In [47]:
det = np.linalg.det(Identity) #using determinant funciton over Identity function , tenth
print(det)

1.0


In [48]:
x = np.array([range(1,6)])
y=np.power(x,2)  
print("square",y)             # To calculate Square using power function ,eleventh


square [[ 1  4  9 16 25]]


In [66]:
print(np.random.rand(3,3))             # To generate Random Matrix whose value lie betweeen(0,1) ,twefth

[[0.24881507 0.02844854 0.1361481 ]
 [0.96173726 0.0297935  0.41963448]
 [0.74850365 0.67513166 0.58049288]]


In [52]:
M1 = [[1,2],[0,1]]
M2 = [[2,1],[1,0]]
print(np.add(M1,M2))             # Matrix Addition , thirteenth

[[3 3]
 [1 1]]


In [53]:
print(np.subtract(M1,M2))          # Matrix subtraction , fourteenth

[[-1  1]
 [-1  1]]


In [61]:
np.sin(np.deg2rad(90))   # To calculate value of sin theta , fifteenth

1.0

In [64]:
np.sqrt(625)  # To calculate square root of given no., sixteenth

25.0